default:
  uptime_checks:
    native:
      enabled: true
    uptimerobot: # Not yet supported
      enabled: false
  hosts:
    a_host:
      url: 'http://example.com'
      status: 200
      interval: 60000
      timeout: 10000
    another_host:
      url: 'http://example.com:1234'
      status: 200
      interval: 60000
      timeout: 30000
  notifications:
    gcm:
      enabled: true
      server_key: '<gcm_server_key>'
      project_number: '<gcm_project_numer>'
      endpoint: 'https://android.googleapis.com/gcm/send'
    pushover: # Not yet supported
      enabled: false
    pushbuller: # Not yet spported
      enabled: false
    email: # Not yet supported
      enabled: false
