default:
  uptime_checks:
    native:
      enabled: true
    uptimerobot: # Not yet supported
      enabled: false
  hosts:
    a_host:
      url: 'http://example.com'
      status: 200 # Expected HTTP status code
      interval: 60 # Seconds
      timeout: 10 # Seconds
    another_host:
      url: 'http://example.com:1234'
      status: 200
      interval: 60
      timeout: 30
  notifications:
    gcm:
      enabled: true
      auth_token: '<gcm_server_key>'
      project_number: '<gcm_project_numer>'
    pushover: # Not yet supported
      enabled: false
    pushbuller: # Not yet spported
      enabled: false
    mailgun:
      enabled: true
      api_key: '<mailgun_api_key>'
      domain: 'example.com'
      from: 'no-reply@example.com'
    development: # Prints out to console for development
      enabled: false
